---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-aws-cert-manager
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: cert-manager
          # anything not staging or prod use this version
          addonChartVersion: '{{metadata.annotations.cert_manager_chart_version}}' # v1.14.3
          addonChartRepository: https://charts.jetstack.io
        selector:
          matchExpressions:
            - key: enable_cert_manager
              operator: In
              values: ['true']
            - key: aws_cluster_name
              operator: Exists
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: '{{metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: '{{values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{metadata.annotations.addons_repo_basepath}}addons/{{values.addonChart}}/values.yaml
              - $values/{{metadata.annotations.addons_repo_basepath}}addons/{{values.addonChart}}/values-{{metadata.annotations.cert_manager_chart_version}}.yaml
            values: |
              serviceAccount:
                name: {{metadata.annotations.cert_manager_service_account}}
                annotations:
                  eks.amazonaws.com/role-arn: {{metadata.annotations.cert_manager_iam_role_arn}}
          # fileParameters:
          #  - name:
          #    path:
          # parameters
          # values
          # valuesObject
      destination:
        namespace: '{{metadata.annotations.cert_manager_namespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
